In [13]:
import pandas as pd

path = '../data/csv/raw_penicillata.csv'

df = pd.read_csv(path)
df

,observed_on,latitude,longitude,place_county_name,place_state_name,url,image_url
0,21/12/1996,"-198,438,339,133","-439,928,264,036",Belo Horizonte,Minas Gerais,https://www.inaturalist.org/observations/24353...,https://inaturalist-open-data.s3.amazonaws.com...
1,29/08/2004,"-198,549,958","-440,053,019",Belo Horizonte,Minas Gerais,https://www.inaturalist.org/observations/42323942,https://inaturalist-open-data.s3.amazonaws.com...
2,05/01/2005,"-23,543,635","-450,624,271",Ubatuba,São Paulo,https://www.inaturalist.org/observations/71310979,https://inaturalist-open-data.s3.amazonaws.com...
3,17/01/2006,-23.55,"-45,066,667",Ubatuba,São Paulo,https://www.inaturalist.org/observations/24402509,https://inaturalist-open-data.s3.amazonaws.com...
4,25/08/2007,"-227,127,432,037","-476,332,621,652",Piracicaba,São Paulo,https://www.inaturalist.org/observations/11159...,https://static.inaturalist.org/photos/18841260...
...,...,...,...,...,...,...,...
1309,23/05/2025,"-237,943,775,525","-470,875,736,659",São Paulo,São Paulo,https://www.inaturalist.org/observations/27495...,https://inaturalist-open-data.s3.amazonaws.com...
1310,24/05/2025,"-229,493,770,556","-470,280,532,778",Belo Horizonte,Minas Gerais,https://www.inaturalist.org/observations/27509...,https://inaturalist-open-data.s3.amazonaws.com...
1311,25/05/2025,"-191,634,792","-454,711,490,997",São Paulo,São Paulo,https://www.inaturalist.org/observations/27528...,https://inaturalist-open-data.s3.amazonaws.com...
1312,25/05/2025,"-234,801,398,091","-463,472,665,474",Cotia,São Paulo,https://www.inaturalist.org/observations/27591...,https://inaturalist-open-data.s3.amazonaws.com...
1313,28/05/2025,"-200,156,817,483","-459,790,701,694",Fernandópolis,São Paulo,https://www.inaturalist.org/observations/28034...,https://static.inaturalist.org/photos/50350153...

In [16]:
df = df[['image_url', 'Tipo']].rename(columns={'image_url': 'url', 'Tipo': 'classe'})

df

                                                    url classe
0     https://inaturalist-open-data.s3.amazonaws.com...   None
1     https://inaturalist-open-data.s3.amazonaws.com...   None
2     https://inaturalist-open-data.s3.amazonaws.com...   None
3     https://inaturalist-open-data.s3.amazonaws.com...   None
4     https://static.inaturalist.org/photos/18841260...   None
...                                                 ...    ...
1309  https://inaturalist-open-data.s3.amazonaws.com...   None
1310  https://inaturalist-open-data.s3.amazonaws.com...   None
1311  https://inaturalist-open-data.s3.amazonaws.com...   None
1312  https://inaturalist-open-data.s3.amazonaws.com...   None
1313  https://static.inaturalist.org/photos/50350153...   None

[1314 rows x 2 columns]

In [17]:
df.to_csv(path, index=False)